import { Color, ColorTheme } from '../types/game';

export const colorThemes: Record<ColorTheme, Color[]> = {
  reds: [
    { id: 'coral', name: 'Coral Blush', hex: '#FF7F7F' },
    { id: 'crimson', name: 'Crimson Red', hex: '#DC143C' },
    { id: 'burgundy', name: 'Deep Burgundy', hex: '#800020' },
    { id: 'rose', name: 'Rose Pink', hex: '#FF69B4' },
    { id: 'cherry', name: 'Cherry Red', hex: '#DE3163' },
    { id: 'scarlet', name: 'Scarlet Fire', hex: '#FF2400' },
    { id: 'maroon', name: 'Rich Maroon', hex: '#800000' },
    { id: 'ruby', name: 'Ruby Red', hex: '#E0115F' },
    { id: 'wine', name: 'Wine Red', hex: '#722F37' },
    { id: 'carmine', name: 'Carmine Red', hex: '#960018' },
    { id: 'raspberry', name: 'Raspberry', hex: '#E30B5D' },
    { id: 'brick', name: 'Brick Red', hex: '#CB4154' },
    { id: 'cardinal', name: 'Cardinal Red', hex: '#C41E3A' },
    { id: 'redwood', name: 'Redwood', hex: '#A45A52' },
    { id: 'venetian', name: 'Venetian Red', hex: '#C80815' },
    { id: 'candy', name: 'Candy Apple', hex: '#FF0800' },
    { id: 'persian', name: 'Persian Red', hex: '#CC3333' },
    { id: 'blood', name: 'Blood Red', hex: '#880808' },
    { id: 'garnet', name: 'Garnet', hex: '#733635' },
    { id: 'vermilion', name: 'Vermilion', hex: '#E34234' },
    { id: 'mahogany', name: 'Mahogany', hex: '#C04000' },
    { id: 'rosewood', name: 'Rosewood', hex: '#65000B' },
    { id: 'carnation', name: 'Carnation', hex: '#FFA6C9' },
    { id: 'merlot', name: 'Merlot', hex: '#541E1B' },
  ],
  blues: [
    { id: 'sky', name: 'Sky Blue', hex: '#87CEEB' },
    { id: 'navy', name: 'Navy Deep', hex: '#000080' },
    { id: 'teal', name: 'Teal Ocean', hex: '#008080' },
    { id: 'ocean', name: 'Ocean Blue', hex: '#006994' },
    { id: 'royal', name: 'Royal Blue', hex: '#4169E1' },
    { id: 'powder', name: 'Powder Blue', hex: '#B0E0E6' },
    { id: 'azure', name: 'Azure Sky', hex: '#007FFF' },
    { id: 'cobalt', name: 'Cobalt Blue', hex: '#0047AB' },
    { id: 'sapphire', name: 'Sapphire Blue', hex: '#0F52BA' },
    { id: 'turquoise', name: 'Turquoise', hex: '#40E0D0' },
    { id: 'indigo', name: 'Indigo Blue', hex: '#4B0082' },
    { id: 'cerulean', name: 'Cerulean', hex: '#2A52BE' },
    { id: 'arctic', name: 'Arctic Blue', hex: '#B0E0E6' },
    { id: 'cornflower', name: 'Cornflower', hex: '#6495ED' },
    { id: 'denim', name: 'Denim Blue', hex: '#1560BD' },
    { id: 'lapis', name: 'Lapis Lazuli', hex: '#26619C' },
    { id: 'steel', name: 'Steel Blue', hex: '#4682B4' },
    { id: 'zaffre', name: 'Zaffre Blue', hex: '#0014A8' },
    { id: 'aquamarine', name: 'Aquamarine', hex: '#7FFFD4' },
    { id: 'periwinkle', name: 'Periwinkle', hex: '#CCCCFF' },
    { id: 'columbia', name: 'Columbia Blue', hex: '#B9D9EB' },
    { id: 'maya', name: 'Maya Blue', hex: '#73C2FB' },
    { id: 'ultramarine', name: 'Ultramarine', hex: '#0437F2' },
    { id: 'prussian', name: 'Prussian Blue', hex: '#003153' },
  ],
  greens: [
    { id: 'sage', name: 'Sage Green', hex: '#9CAF88' },
    { id: 'forest', name: 'Forest Deep', hex: '#228B22' },
    { id: 'mint', name: 'Mint Fresh', hex: '#98FB98' },
    { id: 'olive', name: 'Olive Grove', hex: '#808000' },
    { id: 'emerald', name: 'Emerald Gem', hex: '#50C878' },
    { id: 'lime', name: 'Lime Bright', hex: '#32CD32' },
    { id: 'jade', name: 'Jade Green', hex: '#00A86B' },
    { id: 'moss', name: 'Moss Green', hex: '#8A9A5B' },
    { id: 'fern', name: 'Fern Green', hex: '#4F7942' },
    { id: 'pine', name: 'Pine Green', hex: '#01796F' },
    { id: 'seagreen', name: 'Sea Green', hex: '#2E8B57' },
    { id: 'hunter', name: 'Hunter Green', hex: '#355E3B' },
    { id: 'artichoke', name: 'Artichoke', hex: '#8F9779' },
    { id: 'asparagus', name: 'Asparagus', hex: '#87A96B' },
    { id: 'viridian', name: 'Viridian', hex: '#40826D' },
    { id: 'shamrock', name: 'Shamrock', hex: '#45B1E8' },
    { id: 'malachite', name: 'Malachite', hex: '#0BDA51' },
    { id: 'chartreuse', name: 'Chartreuse', hex: '#7FFF00' },
    { id: 'juniper', name: 'Juniper', hex: '#6B8E23' },
    { id: 'pistachio', name: 'Pistachio', hex: '#93C572' },
    { id: 'basil', name: 'Basil', hex: '#579229' },
    { id: 'kelly', name: 'Kelly Green', hex: '#4CBB17' },
    { id: 'laurel', name: 'Laurel Green', hex: '#A9BA9D' },
    { id: 'thyme', name: 'Thyme Green', hex: '#867E36' },
  ],
  yellows: [
    { id: 'cream', name: 'Cream Silk', hex: '#FFFDD0' },
    { id: 'golden', name: 'Golden Sun', hex: '#FFD700' },
    { id: 'amber', name: 'Amber Glow', hex: '#FFBF00' },
    { id: 'lemon', name: 'Lemon Zest', hex: '#FFF700' },
    { id: 'mustard', name: 'Mustard Field', hex: '#FFDB58' },
    { id: 'butter', name: 'Butter Cream', hex: '#FFFACD' },
    { id: 'canary', name: 'Canary Yellow', hex: '#FFEF00' },
    { id: 'honey', name: 'Honey Gold', hex: '#FFC30B' },
    { id: 'daffodil', name: 'Daffodil', hex: '#FFFF31' },
    { id: 'banana', name: 'Banana Yellow', hex: '#FFE135' },
    { id: 'sunflower', name: 'Sunflower', hex: '#FDB347' },
    { id: 'marigold', name: 'Marigold', hex: '#EAA221' },
    { id: 'jasmine', name: 'Jasmine', hex: '#F8DE7E' },
    { id: 'flax', name: 'Flax Yellow', hex: '#EEDC82' },
    { id: 'corn', name: 'Corn Yellow', hex: '#FFF380' },
    { id: 'pineapple', name: 'Pineapple', hex: '#FFE5B4' },
    { id: 'dandelion', name: 'Dandelion', hex: '#F0E130' },
    { id: 'bumblebee', name: 'Bumblebee', hex: '#FCE205' },
    { id: 'saffron', name: 'Saffron', hex: '#F4C430' },
    { id: 'butterscotch', name: 'Butterscotch', hex: '#FDB347' },
    { id: 'goldenrod', name: 'Goldenrod', hex: '#DAA520' },
    { id: 'medallion', name: 'Medallion', hex: '#C88A65' },
    { id: 'wheat', name: 'Wheat', hex: '#F5DEB3' },
    { id: 'tuscan', name: 'Tuscan Sun', hex: '#FAD6A5' },
  ],
  oranges: [
    { id: 'coral-orange', name: 'Coral Orange', hex: '#FF7F50' },
    { id: 'tangerine', name: 'Tangerine', hex: '#FF8C00' },
    { id: 'peach', name: 'Peach Glow', hex: '#FFCBA4' },
    { id: 'sunset', name: 'Sunset Orange', hex: '#FF4500' },
    { id: 'apricot', name: 'Apricot Soft', hex: '#FBCEB1' },
    { id: 'copper', name: 'Copper Shine', hex: '#B87333' },
    { id: 'rust', name: 'Rust Orange', hex: '#B7410E' },
    { id: 'burnt', name: 'Burnt Orange', hex: '#CC5500' },
    { id: 'carrot', name: 'Carrot Orange', hex: '#ED9121' },
    { id: 'amber-orange', name: 'Amber Orange', hex: '#FF7E00' },
    { id: 'persimmon', name: 'Persimmon', hex: '#EC5800' },
    { id: 'mandarin', name: 'Mandarin', hex: '#FFA500' },
    { id: 'papaya', name: 'Papaya', hex: '#FF9F42' },
    { id: 'kumquat', name: 'Kumquat', hex: '#FB9902' },
    { id: 'macaroon', name: 'Macaroon', hex: '#FFB347' },
    { id: 'mango', name: 'Mango', hex: '#FF8243' },
    { id: 'cantaloupe', name: 'Cantaloupe', hex: '#FFA177' },
    { id: 'tiger', name: 'Tiger Orange', hex: '#FD5E53' },
    { id: 'flame', name: 'Flame Orange', hex: '#FF7D40' },
    { id: 'pumpkin', name: 'Pumpkin', hex: '#FF7518' },
    { id: 'ochre', name: 'Ochre', hex: '#CC7722' },
    { id: 'bronze', name: 'Bronze', hex: '#CD7F32' },
    { id: 'terracotta', name: 'Terracotta', hex: '#E2725B' },
    { id: 'cinnamon', name: 'Cinnamon', hex: '#D2691E' },
  ],
  mixed: [
    { id: 'lavender', name: 'Lavender', hex: '#E6E6FA' },
    { id: 'coral-mixed', name: 'Coral Blush', hex: '#FF7F7F' },
    { id: 'sage-mixed', name: 'Sage Green', hex: '#9CAF88' },
    { id: 'golden-mixed', name: 'Golden Sun', hex: '#FFD700' },
    { id: 'sky-mixed', name: 'Sky Blue', hex: '#87CEEB' },
    { id: 'plum', name: 'Plum Purple', hex: '#8E4585' },
    { id: 'orchid', name: 'Orchid Pink', hex: '#DA70D6' },
    { id: 'sienna', name: 'Sienna Brown', hex: '#A0522D' },
    { id: 'violet', name: 'Violet Purple', hex: '#8B00FF' },
    { id: 'magenta', name: 'Magenta Pink', hex: '#FF00FF' },
    { id: 'teal-mixed', name: 'Teal Blue', hex: '#008080' },
    { id: 'maroon-mixed', name: 'Maroon Red', hex: '#800000' },
    { id: 'slate', name: 'Slate Gray', hex: '#708090' },
    { id: 'rose-gold', name: 'Rose Gold', hex: '#B76E79' },
    { id: 'amethyst', name: 'Amethyst', hex: '#9966CC' },
    { id: 'burgundy-mixed', name: 'Burgundy Wine', hex: '#800020' },
    { id: 'azure-mixed', name: 'Azure Blue', hex: '#007FFF' },
    { id: 'coral-pink', name: 'Coral Pink', hex: '#F88379' },
    { id: 'olive-mixed', name: 'Olive Green', hex: '#808000' },
    { id: 'indigo-mixed', name: 'Indigo Blue', hex: '#4B0082' },
    { id: 'mauve', name: 'Mauve Purple', hex: '#E0B0FF' },
    { id: 'taupe', name: 'Taupe Brown', hex: '#483C32' },
    { id: 'periwinkle-mixed', name: 'Periwinkle Blue', hex: '#CCCCFF' },
    { id: 'cerise', name: 'Cerise Pink', hex: '#DE3163' },
  ],
};

export const themeDisplayNames: Record<ColorTheme, string> = {
  reds: 'Reds',
  blues: 'Blues', 
  greens: 'Greens',
  yellows: 'Yellows',
  oranges: 'Oranges',
  mixed: 'Mixed',
};

export function generateGameCards(theme: ColorTheme): Color[] {
  const colors = colorThemes[theme];
  // Create pairs by duplicating each color
  return [...colors, ...colors];
}